version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg_networkflow
    environment:
      POSTGRES_USER: nfuser
      POSTGRES_PASSWORD: nfpass
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_networkflow
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - postgres
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
